name: Capture a Link
description: Capture a link for further research.
title: "[Link]: "
body:
  - type: input
    id: title
    attributes:
      label: Title
      description: In a few words, what is this link about?
  - type: input
    id: link
    attributes:
      label: URL
      description: What is the web address for the link?
      placeholder: https://
  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Why is this link important?
  - type: dropdown
    id: topic
    attributes:
      label: Topic
      description: Which topic does this link relate to?
      multiple: false
      options:
        - Religion
        - Technology
        - Cartography
        - Productivity